site_name: meadapt.com

# Repository
repo_name: meadapt/meadapt.com
repo_url: https://github.com/meadapt/meadapt.com
edit_uri: edit/main/docs/
site_description: >-
  Aprenda RPA com Power Automate de forma simples e descomplicada.
  A MeAdapt te ajuda a dominar novas tecnologias com cursos práticos e acessíveis.
  Tudo pensado para que você supere qualquer desafio tecnológico.

nav:
  - Home: index.md
  - Vem conhecer: /#vem-conhecer
  - Sobre Nós: sobre_nos.md
  - Blog: blog/index.md

# Configuration
theme:
  name: material
  icon:
    logo: octicons/code-review-16
    edit: material/pencil
    view: material/eye
  favicon: assets/favicon.svg
  language: pt
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.action.edit
    - content.action.view
  palette:
    - scheme: dark-blue
  font:
    text: Plus Jakarta Sans
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - abbr
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/style.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - assets/style.js
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
  - assets/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra: # Footer
  social:
    - icon: fontawesome/brands/youtube
      name: My YouTube Channel.
      link: https://www.youtube.com/channel/UCoMuk7Pk3VzUYQtuqa6fLTw
    - icon: simple/github
      name: My GitHub Account.
      link: http://github.com/meadapt
  analytics:
    provider: google
    property: G-0QEE78N4QK
    feedback:
      title: Gostou desta página?
      ratings:
        - icon: material/thumb-up-outline
          name: Gostei
          data: 1
          note: >-
            Obrigado por compartilhar!
        - icon: material/thumb-down-outline
          name: Não gostei
          data: 0
          note: >-
            Obrigado por compartilhar!
            Adoraria escutar um pouquinho mais sua opinião.
            Se estiver a vontade quanto a isso peço que nos envio no email suporte@meadapt.com!


plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      enable_creation_date: true
  - search:
      lang:
        - pt
  - blog:
      post_url_format: "{slug}"
      archive: false
      categories_toc: true
      post_excerpt: required
  - mkdocs-video:
      video_muted: True
      video_controls: True
      video_autoplay: False

watch:
  - includes
