authors:
  gabrielbdornas:
    name: Gabriel Braico Dornas
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/49699290
  raianecardoso:
    name: Raiane Cardoso de Souza
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/166438302?v=4
